image: node:latest
stages:
  - publish

# 全局 before_script，適用於所有階段
before_script:
  - npm install --global corepack@latest
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm config set store-dir .pnpm-store

publish:
  stage: publish
  script:
    - echo CI_PROJECT_ID $CI_PROJECT_ID
    - echo CI_JOB_TOKEN $CI_JOB_TOKEN
    - echo "@game:registry=https://gitlab.sao-x.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.sao-x.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.sao-x.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - pnpm install --frozen-lockfile
    - pnpm build
    - ls -al
    - pnpm publish --no-git-checks
