# include:
#   - local: .gitlab/workflows/docker.gitlab-ci.yml
stages:
  - install
  - build

before_script:
  - export SHELL=/bin/bash
  - npm install --global corepack@latest
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - export PNPM_HOME="/root/.local/share/pnpm"
  - export PATH="$PNPM_HOME:$PATH"
  - pnpm setup
  - pnpm config set store-dir .pnpm-store
  - pnpm install -g turbo@latest
  # ⬇️ 確保 Git 比較時能抓到 Merge Request 的目標分支
  - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --depth=1

install_dependencies:
  stage: install
  image: node:18
  script:
    - turbo -h

build:
  stage: build
  image: node:18
  script:
    # 告訴 turbo 要比較哪個 base 分支
    - export TURBO_SCM_BASE=origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - turbo run build --affected
  only:
    - merge_requests
