services:
  web:
    image: 192.168.2.40:5005/msi/monorepo/web:main
    ports:
      - '3001:3000' # host:container
    environment:
      - NODE_ENV=production
    restart: always

  # docs:
  #   image: 192.168.2.40:5005/msi/monorepo/docs:main
  #   ports:
  #     - '3002:3000'
  #   environment:
  #     - NODE_ENV=production
  #   restart: always

  # 可以持續新增其他子專案
  # projectX:
  #   build:
  #     context: .
  #     dockerfile: apps/projectX/Dockerfile
  #   ports:
  #     - "3003:3000"
