stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME

web-build:
  stage: build
  image: docker:latest
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  services:
    - name: docker:dind
      command: ['--insecure-registry=192.168.2.40:5005']
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - echo "Building Docker image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f ./apps/web/Dockerfile -t $IMAGE_TAG . --build-arg TURBO_TEAM=$TURBO_TEAM --build-arg TURBO_TOKEN=$TURBO_TOKEN --no-cache
    - docker push $IMAGE_TAG

web-deploy:
  stage: deploy
  image: debian:bullseye
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > deploy.pem
    - chmod 400 deploy.pem
    - ssh-add deploy.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "🚀 查看伺服器 Docker 狀態"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "docker images && docker ps -a"
    - echo "📤 傳輸 docker-compose.yml 至伺服器 docker/msi 目錄"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "mkdir -p /home/${SSH_USER}/docker/msi"
    - scp $(pwd)/docker-compose.yml ${SSH_USER}@${SSH_SERVER_IP}:/home/${SSH_USER}/docker/msi/
    - echo "🧹 停止並移除現有容器"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "cd /home/${SSH_USER}/docker/msi && docker compose down"
    - echo "🔄 拉取最新映像檔"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "docker pull $IMAGE_TAG"
    - echo "🆙 使用 docker-compose 啟動服務"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "cd /home/${SSH_USER}/docker/msi && docker compose up -d"
    - echo "✅ 部署完成，查看運行中的容器"
    - ssh ${SSH_USER}@${SSH_SERVER_IP} "docker ps"
