export interface AppConfig {
  NEXT_PUBLIC_RD_SITE_URL: string
  NEXT_PUBLIC_LOGIN_API_URL: string
  NEXT_PUBLIC_BASE_PATH_URL: string
  NEXT_PUBLIC_COOKIE_DOMAIN: string
  NEXT_PUBLIC_NIM_SERVICE_API_URL: string
  NEXT_PUBLIC_PATENT_SERVICE_API_URL: string
  NEXT_PUBLIC_AI_API_URL: string
  NEXT_PUBLIC_VGA_AI_API_URL: string
  NEXT_PUBLIC_POSTHOG_KEY: string
  NEXT_PUBLIC_POSTHOG_HOST: string
  // 其他所有您需要的變數
}

/**
 * 根據環境變數取得對應的環境配置
 * 這些變數現在由 .env 檔案提供，並在部署時根據環境解密
 */
export function getAppConfig(): AppConfig {
  return {
    NEXT_PUBLIC_RD_SITE_URL: process.env.NEXT_PUBLIC_RD_SITE_URL || '',
    NEXT_PUBLIC_LOGIN_API_URL: process.env.NEXT_PUBLIC_LOGIN_API_URL || '',
    NEXT_PUBLIC_BASE_PATH_URL: process.env.NEXT_PUBLIC_BASE_PATH_URL || '/AI_City',
    NEXT_PUBLIC_COOKIE_DOMAIN: process.env.NEXT_PUBLIC_COOKIE_DOMAIN || '',
    NEXT_PUBLIC_NIM_SERVICE_API_URL: process.env.NEXT_PUBLIC_NIM_SERVICE_API_URL || '',
    NEXT_PUBLIC_PATENT_SERVICE_API_URL: process.env.NEXT_PUBLIC_PATENT_SERVICE_API_URL || '',
    NEXT_PUBLIC_AI_API_URL: process.env.NEXT_PUBLIC_AI_API_URL || '',
    NEXT_PUBLIC_VGA_AI_API_URL: process.env.NEXT_PUBLIC_VGA_AI_API_URL || '',
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY || '',
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST || ''
  }
}
