import type { Metadata } from 'next'
import { PostHogProvider } from '@msi/ui'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import React from 'react'
import { Toaster } from 'sonner'
import BannerWrapper from '@/components/banner/BannerWrapper'
import { LanguageProvider } from '@/context/Language'
import Providers from './providers'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'RD AI City - AI平台',
  description: 'Generated by create next app',
  icons: {
    //   icon: 'https://rd_service.msi.com.tw/sdqaFile/AI%20Platform_Test/msi-asr/Logo-Icon.png'
    icon: 'https://rd_service.msi.com.tw/sdqaFile/AI%20Platform_Test/msi-asr/Logo-City.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[auto_1fr] min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="leight"
          // enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          <LanguageProvider>
            <PostHogProvider>
              <NuqsAdapter>
                <Providers>
                  <BannerWrapper />
                  {children}
                  <Toaster richColors />
                </Providers>
              </NuqsAdapter>
            </PostHogProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
