import type { Locale } from '@msi/i18n'
import type { Metadata } from 'next'
import { I18nProvider } from '@msi/i18n'
import { PostHogProvider } from '@msi/ui'
import { getLocale } from 'next-intl/server'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import React from 'react'
import { Toaster } from 'sonner'
import BannerWrapper from '@/components/banner/BannerWrapper'
import { LanguageProvider } from '@/context/Language'

// 預先載入所有語系的翻譯
import enMessages from '../../messages/en.json'
import zhTWMessages from '../../messages/zh-TW.json'

import Providers from './providers'
import './globals.css'

const allMessages = {
  'en': enMessages,
  'zh-TW': zhTWMessages,
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'RD AI City - AI平台',
  description: 'Generated by create next app',
  icons: {
    //   icon: 'https://rd_service.msi.com.tw/sdqaFile/AI%20Platform_Test/msi-asr/Logo-Icon.png'
    icon: 'https://rd_service.msi.com.tw/sdqaFile/AI%20Platform_Test/msi-asr/Logo-City.png',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale() as Locale

  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[auto_1fr] min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="leight"
          // enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          <LanguageProvider>
            <PostHogProvider>
              <NuqsAdapter>
                <I18nProvider
                  initialLocale={locale}
                  allMessages={allMessages}
                >
                  <Providers>
                    <BannerWrapper />
                    {children}
                    <Toaster richColors />
                  </Providers>
                </I18nProvider>
              </NuqsAdapter>
            </PostHogProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
