import type { Metadata } from "next";

import "./globals.css";

import { PageBreadcrumb } from "@msi/ui/components/layout/breadcrumb/page-breadcrumb";
import Footer from "@msi/ui/components/layout/footer";
import { AppSidebar } from "@msi/ui/components/layout/sidebar/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@msi/ui/components/sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";

import { BREADCRUMB_CONFIG } from "../../config/breadcrumb";
import { SIDEBAR_CONFIG } from "../../config/sidebar";

import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "數據圖形化系統",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen grid-rows-[auto_1fr] antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          <NuqsAdapter>
            <Providers>
              <SidebarProvider>
                <AppSidebar items={SIDEBAR_CONFIG["/"]} />
                <SidebarInset>
                  <div className="flex min-h-screen flex-col">
                    <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
                      <SidebarTrigger className="-ml-1" />
                    </header>
                    <main className="container mx-auto flex-1 p-4 sm:px-6 lg:px-8">
                      <PageBreadcrumb config={BREADCRUMB_CONFIG} />
                      {children}
                    </main>
                    <Footer />
                  </div>
                </SidebarInset>
              </SidebarProvider>
              <Toaster richColors />
            </Providers>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
