import type { Metadata } from 'next'
import { PageBreadcrumb } from '@msi/ui/components/layout/breadcrumb/page-breadcrumb'
import { AppSidebar } from '@msi/ui/components/layout/sidebar/app-sidebar'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from 'sonner'
import Banner from '@/components/banner'
import { BREADCRUMB_LABELS } from '../../config/breadcrumb'
import { getSidebarItems } from '../../config/sidebar'
import Providers from './providers'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: '數據圖形化系統',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Since this is a server component, we can't use usePathname here.
  // We will pass the sidebar items directly to the client component.
  // For the purpose of this layout, we'll fetch the default sidebar items.
  // A more advanced implementation might involve a context or a different layout structure
  // if the sidebar needs to be dynamically updated based on client-side navigation
  // without a full page reload.
  const sidebarItems = getSidebarItems('/') // Default to root path for the main layout

  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[auto_1fr] min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="leight"
          // enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          <NuqsAdapter>
            <Providers>
              <div className="flex">
                <AppSidebar items={sidebarItems} />
                <div className="flex-1 flex flex-col">
                  <Banner />
                  <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-4">
                    <PageBreadcrumb labels={BREADCRUMB_LABELS} />
                    {children}
                  </main>
                </div>
              </div>
              <Toaster richColors />
            </Providers>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  )
}
