import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { titleConfig } from '@/config/title'

export async function generateMetadata(): Promise<Metadata> {
  const headersList = await headers()
  const header_url = decodeURIComponent(headersList.get('x-url') || '').split('AI_City')[1] || '/'
  const matchedTitle = titleConfig.find(item => header_url.startsWith(item.pathname))?.title || '首頁'
  return {
    title: `RD AI City - ${matchedTitle}`,
    description: 'Generated by create next app',
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      {children}
    </>
  )
}
